[rospy.client][INFO] 2017-06-09 18:41:53,396: init_node, name[/marker_control_13450_1497058913346], pid[13450]
[xmlrpc][INFO] 2017-06-09 18:41:53,397: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-06-09 18:41:53,401: Started XML-RPC server [http://ip-172-31-19-100:38675/]
[rospy.init][INFO] 2017-06-09 18:41:53,401: ROS Slave URI: [http://ip-172-31-19-100:38675/]
[rospy.impl.masterslave][INFO] 2017-06-09 18:41:53,405: _ready: http://ip-172-31-19-100:38675/
[xmlrpc][INFO] 2017-06-09 18:41:53,412: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-06-09 18:41:53,413: Registering with master node http://localhost:37427
[rospy.init][INFO] 2017-06-09 18:41:53,508: registered with master
[rospy.rosout][INFO] 2017-06-09 18:41:53,512: initializing /rosout core topic
[rospy.rosout][INFO] 2017-06-09 18:41:53,521: connected to core topic /rosout
[rospy.simtime][INFO] 2017-06-09 18:41:53,525: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-06-09 18:41:53,761: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-06-09 18:41:53,780: topic[/collision_object] adding connection to [/move_group], count 0
[rospy.internal][INFO] 2017-06-09 18:41:53,784: topic[/attached_collision_object] adding connection to [/move_group], count 0
[rospy.internal][INFO] 2017-06-09 18:41:53,868: topic[/control_markers/update] adding connection to [/interactive_marker_proxy], count 0
[rospy.internal][INFO] 2017-06-09 18:41:54,271: topic[/control_markers/update_full] adding connection to [/interactive_marker_proxy], count 0
[rospy.internal][INFO] 2017-06-09 18:41:57,697: topic[/visualization_marker_array] adding connection to [/rosbridge_websocket], count 0
[rospy.internal][INFO] 2017-06-09 18:41:57,819: topic[/control_markers/feedback] adding connection to [http://ip-172-31-19-100:52336/], count 0
[rospy.internal][INFO] 2017-06-09 18:42:15,375: topic[/joint_trajectory] adding connection to [http://ip-172-31-19-100:59354/], count 0
[rospy.internal][INFO] 2017-06-09 18:42:15,379: topic[/motion_planning_goal] adding connection to [/move_arm_14513_1497058934975], count 0
[rospy.internal][ERROR] 2017-06-09 18:42:48,372: Unable to initiate TCP/IP socket to ip-172-31-19-100:47084 (http://ip-172-31-19-100:59354/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2017-06-09 18:42:49,645: Unknown error initiating TCP/IP socket to ip-172-31-19-100:47084 (http://ip-172-31-19-100:59354/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2017-06-09 18:42:49,648: topic[/joint_trajectory] removing connection to http://ip-172-31-19-100:59354/
[rospy.internal][INFO] 2017-06-09 18:43:23,744: topic[/joint_trajectory] adding connection to [http://ip-172-31-19-100:60967/], count 0
[rospy.internal][INFO] 2017-06-09 18:43:23,747: topic[/motion_planning_goal] adding connection to [/move_arm_15160_1497059003331], count 1
[rospy.internal][ERROR] 2017-06-09 18:50:41,322: Unable to initiate TCP/IP socket to ip-172-31-19-100:47405 (http://ip-172-31-19-100:60967/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2017-06-09 18:50:42,512: Unknown error initiating TCP/IP socket to ip-172-31-19-100:47405 (http://ip-172-31-19-100:60967/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2017-06-09 18:50:42,517: topic[/joint_trajectory] removing connection to http://ip-172-31-19-100:60967/
[rospy.internal][INFO] 2017-06-09 18:51:23,491: topic[/joint_trajectory] adding connection to [http://ip-172-31-19-100:54395/], count 0
[rospy.internal][INFO] 2017-06-09 18:51:23,493: topic[/motion_planning_goal] adding connection to [/move_arm_28290_1497059483075], count 2
[rospy.internal][INFO] 2017-06-09 18:51:23,496: topic[/motion_planning_goal] removing connection to /move_arm_14513_1497058934975
[rospy.internal][ERROR] 2017-06-09 18:51:45,889: Unable to initiate TCP/IP socket to ip-172-31-19-100:42308 (http://ip-172-31-19-100:54395/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2017-06-09 18:51:47,138: Unknown error initiating TCP/IP socket to ip-172-31-19-100:42308 (http://ip-172-31-19-100:54395/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2017-06-09 18:51:47,142: topic[/joint_trajectory] removing connection to http://ip-172-31-19-100:54395/
[rospy.internal][INFO] 2017-06-09 18:53:01,919: topic[/joint_trajectory] adding connection to [http://ip-172-31-19-100:36835/], count 0
[rospy.internal][INFO] 2017-06-09 18:53:01,922: topic[/motion_planning_goal] adding connection to [/move_arm_4154_1497059581499], count 2
[rospy.internal][INFO] 2017-06-09 18:53:01,926: topic[/motion_planning_goal] removing connection to /move_arm_15160_1497059003331
[rospy.internal][ERROR] 2017-06-09 18:57:32,052: Unable to initiate TCP/IP socket to ip-172-31-19-100:54955 (http://ip-172-31-19-100:36835/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2017-06-09 18:57:33,254: Unknown error initiating TCP/IP socket to ip-172-31-19-100:54955 (http://ip-172-31-19-100:36835/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2017-06-09 18:57:33,258: topic[/joint_trajectory] removing connection to http://ip-172-31-19-100:36835/
[rospy.internal][INFO] 2017-06-09 18:57:37,980: topic[/joint_trajectory] adding connection to [http://ip-172-31-19-100:36575/], count 0
[rospy.internal][INFO] 2017-06-09 18:57:38,987: topic[/motion_planning_goal] adding connection to [/move_arm_20785_1497059857573], count 2
[rospy.internal][INFO] 2017-06-09 18:57:38,991: topic[/motion_planning_goal] removing connection to /move_arm_28290_1497059483075
[rospy.internal][ERROR] 2017-06-09 19:00:38,680: Unable to initiate TCP/IP socket to ip-172-31-19-100:37672 (http://ip-172-31-19-100:36575/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2017-06-09 19:00:39,835: Unknown error initiating TCP/IP socket to ip-172-31-19-100:37672 (http://ip-172-31-19-100:36575/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2017-06-09 19:00:39,836: topic[/joint_trajectory] removing connection to http://ip-172-31-19-100:36575/
[rospy.internal][INFO] 2017-06-09 19:00:42,901: topic[/joint_trajectory] adding connection to [http://ip-172-31-19-100:52130/], count 0
[rospy.internal][INFO] 2017-06-09 19:00:42,908: topic[/motion_planning_goal] adding connection to [/move_arm_7824_1497060042452], count 2
[rospy.internal][INFO] 2017-06-09 19:00:42,917: topic[/motion_planning_goal] removing connection to /move_arm_4154_1497059581499
[rospy.internal][ERROR] 2017-06-09 19:04:51,440: Unable to initiate TCP/IP socket to ip-172-31-19-100:45569 (http://ip-172-31-19-100:52130/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2017-06-09 19:04:52,677: Unknown error initiating TCP/IP socket to ip-172-31-19-100:45569 (http://ip-172-31-19-100:52130/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2017-06-09 19:04:52,681: topic[/joint_trajectory] removing connection to http://ip-172-31-19-100:52130/
[rospy.internal][INFO] 2017-06-09 19:04:55,241: topic[/joint_trajectory] adding connection to [http://ip-172-31-19-100:39212/], count 0
[rospy.internal][INFO] 2017-06-09 19:04:55,248: topic[/motion_planning_goal] adding connection to [/move_arm_27134_1497060294848], count 2
[rospy.internal][INFO] 2017-06-09 19:04:55,252: topic[/motion_planning_goal] removing connection to /move_arm_20785_1497059857573
[rospy.internal][INFO] 2017-06-09 19:05:09,920: topic[/motion_planning_goal] removing connection to /move_arm_7824_1497060042452
[rospy.internal][INFO] 2017-06-09 19:06:25,601: topic[/joint_states] adding connection to [http://ip-172-31-19-100:47311/], count 0
[rospy.internal][INFO] 2017-06-09 19:06:25,602: topic[/tf] adding connection to [http://ip-172-31-19-100:59205/], count 0
[rospy.internal][INFO] 2017-06-09 19:06:25,802: topic[/joint_command] adding connection to [/robot_sim], count 0
[rospy.internal][INFO] 2017-06-09 19:06:46,632: topic[/control_markers/update_full] removing connection to /interactive_marker_proxy
[rospy.internal][ERROR] 2017-06-09 19:07:24,684: Unable to initiate TCP/IP socket to ip-172-31-19-100:42802 (http://ip-172-31-19-100:39212/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2017-06-09 19:07:25,686: Unknown error initiating TCP/IP socket to ip-172-31-19-100:42802 (http://ip-172-31-19-100:39212/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2017-06-09 19:07:25,690: topic[/joint_trajectory] removing connection to http://ip-172-31-19-100:39212/
