[rospy.client][INFO] 2017-06-09 18:30:13,896: init_node, name[/marker_control_4416_1497058213851], pid[4416]
[xmlrpc][INFO] 2017-06-09 18:30:13,897: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-06-09 18:30:13,900: Started XML-RPC server [http://ip-172-31-26-229:40402/]
[rospy.init][INFO] 2017-06-09 18:30:13,901: ROS Slave URI: [http://ip-172-31-26-229:40402/]
[rospy.impl.masterslave][INFO] 2017-06-09 18:30:13,905: _ready: http://ip-172-31-26-229:40402/
[xmlrpc][INFO] 2017-06-09 18:30:13,913: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-06-09 18:30:13,913: Registering with master node http://localhost:55471
[rospy.init][INFO] 2017-06-09 18:30:14,009: registered with master
[rospy.rosout][INFO] 2017-06-09 18:30:14,012: initializing /rosout core topic
[rospy.rosout][INFO] 2017-06-09 18:30:14,022: connected to core topic /rosout
[rospy.simtime][INFO] 2017-06-09 18:30:14,027: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-06-09 18:30:14,233: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-06-09 18:30:14,329: topic[/collision_object] adding connection to [/move_group], count 0
[rospy.internal][INFO] 2017-06-09 18:30:14,333: topic[/attached_collision_object] adding connection to [/move_group], count 0
[rospy.internal][INFO] 2017-06-09 18:30:14,336: topic[/control_markers/update] adding connection to [/interactive_marker_proxy], count 0
[rospy.internal][INFO] 2017-06-09 18:30:14,734: topic[/control_markers/update_full] adding connection to [/interactive_marker_proxy], count 0
[rospy.internal][INFO] 2017-06-09 18:30:25,212: topic[/visualization_marker_array] adding connection to [/rosbridge_websocket], count 0
[rospy.internal][INFO] 2017-06-09 18:30:25,306: topic[/control_markers/feedback] adding connection to [http://ip-172-31-26-229:34207/], count 0
[rospy.internal][INFO] 2017-06-09 18:30:41,374: topic[/joint_trajectory] adding connection to [http://ip-172-31-26-229:46098/], count 0
[rospy.internal][INFO] 2017-06-09 18:30:42,231: topic[/motion_planning_goal] adding connection to [/move_arm_5528_1497058240988], count 0
[rospy.internal][ERROR] 2017-06-09 18:31:10,867: Unable to initiate TCP/IP socket to ip-172-31-26-229:50499 (http://ip-172-31-26-229:46098/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2017-06-09 18:31:12,009: Unknown error initiating TCP/IP socket to ip-172-31-26-229:50499 (http://ip-172-31-26-229:46098/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2017-06-09 18:31:12,019: topic[/joint_trajectory] removing connection to http://ip-172-31-26-229:46098/
[rospy.internal][ERROR] 2017-06-09 18:37:07,865: Unable to initiate TCP/IP socket to ip-172-31-26-229:35258 (http://ip-172-31-26-229:34207/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: Internal error processing topic [/control_markers/feedback]

[rospy.internal][ERROR] 2017-06-09 18:37:08,867: Unable to initiate TCP/IP socket to ip-172-31-26-229:35258 (http://ip-172-31-26-229:34207/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: [/rosbridge_websocket] is not a publisher of [/control_markers/feedback]. Topics are [['/rosout', 'rosgraph_msgs/Log']]

