[rospy.client][INFO] 2017-06-09 15:52:28,750: init_node, name[/marker_control_3042_1497048748704], pid[3042]
[xmlrpc][INFO] 2017-06-09 15:52:28,750: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-06-09 15:52:28,754: Started XML-RPC server [http://ip-172-31-26-229:41481/]
[rospy.init][INFO] 2017-06-09 15:52:28,754: ROS Slave URI: [http://ip-172-31-26-229:41481/]
[rospy.impl.masterslave][INFO] 2017-06-09 15:52:28,757: _ready: http://ip-172-31-26-229:41481/
[rospy.registration][INFO] 2017-06-09 15:52:28,765: Registering with master node http://localhost:41193
[xmlrpc][INFO] 2017-06-09 15:52:28,765: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2017-06-09 15:52:28,861: registered with master
[rospy.rosout][INFO] 2017-06-09 15:52:28,865: initializing /rosout core topic
[rospy.rosout][INFO] 2017-06-09 15:52:28,875: connected to core topic /rosout
[rospy.simtime][INFO] 2017-06-09 15:52:28,880: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-06-09 15:52:29,157: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-06-09 15:52:29,182: topic[/collision_object] adding connection to [/move_group], count 0
[rospy.internal][INFO] 2017-06-09 15:52:29,186: topic[/attached_collision_object] adding connection to [/move_group], count 0
[rospy.internal][INFO] 2017-06-09 15:52:29,190: topic[/control_markers/update] adding connection to [/interactive_marker_proxy], count 0
[rospy.internal][INFO] 2017-06-09 15:52:29,588: topic[/control_markers/update_full] adding connection to [/interactive_marker_proxy], count 0
[rospy.internal][INFO] 2017-06-09 15:52:52,384: topic[/visualization_marker_array] adding connection to [/rosbridge_websocket], count 0
[rospy.internal][INFO] 2017-06-09 15:52:52,408: topic[/control_markers/feedback] adding connection to [http://ip-172-31-26-229:33014/], count 0
[rospy.internal][INFO] 2017-06-09 15:53:29,869: topic[/joint_trajectory] adding connection to [http://ip-172-31-26-229:60007/], count 0
[rospy.internal][INFO] 2017-06-09 15:53:29,875: topic[/motion_planning_goal] adding connection to [/move_arm_4623_1497048809421], count 0
[rospy.internal][INFO] 2017-06-09 15:54:25,815: topic[/tf] adding connection to [http://ip-172-31-26-229:36106/], count 0
[rospy.internal][INFO] 2017-06-09 15:54:25,816: topic[/joint_states] adding connection to [http://ip-172-31-26-229:43268/], count 0
[rospy.internal][INFO] 2017-06-09 15:54:26,046: topic[/joint_command] adding connection to [/robot_sim], count 0
[rospy.internal][INFO] 2017-06-09 15:54:31,119: topic[/control_markers/update_full] removing connection to /interactive_marker_proxy
[rospy.internal][ERROR] 2017-06-09 15:54:41,133: Unable to initiate TCP/IP socket to ip-172-31-26-229:37216 (http://ip-172-31-26-229:60007/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2017-06-09 15:54:42,290: Unknown error initiating TCP/IP socket to ip-172-31-26-229:37216 (http://ip-172-31-26-229:60007/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2017-06-09 15:54:42,294: topic[/joint_trajectory] removing connection to http://ip-172-31-26-229:60007/
[rospy.internal][ERROR] 2017-06-09 16:54:34,753: Unable to initiate TCP/IP socket to ip-172-31-26-229:36529 (http://ip-172-31-26-229:33014/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: Internal error processing topic [/control_markers/feedback]

[rospy.internal][ERROR] 2017-06-09 16:54:35,756: Unable to initiate TCP/IP socket to ip-172-31-26-229:36529 (http://ip-172-31-26-229:33014/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: [/rosbridge_websocket] is not a publisher of [/control_markers/feedback]. Topics are [['/rosout', 'rosgraph_msgs/Log']]

[rospy.internal][ERROR] 2017-06-09 16:54:37,761: Unable to initiate TCP/IP socket to ip-172-31-26-229:36529 (http://ip-172-31-26-229:33014/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: [/rosbridge_websocket] is not a publisher of [/control_markers/feedback]. Topics are [['/rosout', 'rosgraph_msgs/Log']]

[rospy.internal][ERROR] 2017-06-09 16:54:41,770: Unable to initiate TCP/IP socket to ip-172-31-26-229:36529 (http://ip-172-31-26-229:33014/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: [/rosbridge_websocket] is not a publisher of [/control_markers/feedback]. Topics are [['/rosout', 'rosgraph_msgs/Log']]

[rospy.internal][ERROR] 2017-06-09 16:54:49,779: Unable to initiate TCP/IP socket to ip-172-31-26-229:36529 (http://ip-172-31-26-229:33014/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: [/rosbridge_websocket] is not a publisher of [/control_markers/feedback]. Topics are [['/rosout', 'rosgraph_msgs/Log']]

[rospy.internal][ERROR] 2017-06-09 16:55:05,800: Unable to initiate TCP/IP socket to ip-172-31-26-229:36529 (http://ip-172-31-26-229:33014/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: [/rosbridge_websocket] is not a publisher of [/control_markers/feedback]. Topics are [['/rosout', 'rosgraph_msgs/Log']]

[rospy.internal][ERROR] 2017-06-09 16:55:37,834: Unable to initiate TCP/IP socket to ip-172-31-26-229:36529 (http://ip-172-31-26-229:33014/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: [/rosbridge_websocket] is not a publisher of [/control_markers/feedback]. Topics are [['/rosout', 'rosgraph_msgs/Log']]

[rospy.internal][ERROR] 2017-06-09 16:56:41,899: Unable to initiate TCP/IP socket to ip-172-31-26-229:36529 (http://ip-172-31-26-229:33014/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: [/rosbridge_websocket] is not a publisher of [/control_markers/feedback]. Topics are [['/rosout', 'rosgraph_msgs/Log']]

[rospy.internal][ERROR] 2017-06-09 16:58:50,001: Unable to initiate TCP/IP socket to ip-172-31-26-229:36529 (http://ip-172-31-26-229:33014/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: [/rosbridge_websocket] is not a publisher of [/control_markers/feedback]. Topics are [['/rosout', 'rosgraph_msgs/Log']]

[rospy.internal][ERROR] 2017-06-09 17:03:06,100: Unable to initiate TCP/IP socket to ip-172-31-26-229:36529 (http://ip-172-31-26-229:33014/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: [/rosbridge_websocket] is not a publisher of [/control_markers/feedback]. Topics are [['/rosout', 'rosgraph_msgs/Log']]

[rospy.internal][ERROR] 2017-06-09 17:11:38,202: Unable to initiate TCP/IP socket to ip-172-31-26-229:36529 (http://ip-172-31-26-229:33014/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: [/rosbridge_websocket] is not a publisher of [/control_markers/feedback]. Topics are [['/rosout', 'rosgraph_msgs/Log']]

[rospy.internal][ERROR] 2017-06-09 17:28:42,299: Unable to initiate TCP/IP socket to ip-172-31-26-229:36529 (http://ip-172-31-26-229:33014/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: [/rosbridge_websocket] is not a publisher of [/control_markers/feedback]. Topics are [['/rosout', 'rosgraph_msgs/Log']]

