[rospy.client][INFO] 2017-06-09 18:18:59,002: init_node, name[/marker_control_5973_1497057538941], pid[5973]
[xmlrpc][INFO] 2017-06-09 18:18:59,003: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-06-09 18:18:59,007: Started XML-RPC server [http://ip-172-31-26-229:59695/]
[rospy.impl.masterslave][INFO] 2017-06-09 18:18:59,011: _ready: http://ip-172-31-26-229:59695/
[rospy.init][INFO] 2017-06-09 18:18:59,007: ROS Slave URI: [http://ip-172-31-26-229:59695/]
[xmlrpc][INFO] 2017-06-09 18:18:59,015: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-06-09 18:18:59,016: Registering with master node http://localhost:32860
[rospy.init][INFO] 2017-06-09 18:18:59,119: registered with master
[rospy.rosout][INFO] 2017-06-09 18:18:59,123: initializing /rosout core topic
[rospy.rosout][INFO] 2017-06-09 18:18:59,133: connected to core topic /rosout
[rospy.simtime][INFO] 2017-06-09 18:18:59,138: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-06-09 18:18:59,413: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-06-09 18:18:59,424: topic[/control_markers/update] adding connection to [/interactive_marker_proxy], count 0
[rospy.internal][INFO] 2017-06-09 18:18:59,439: topic[/collision_object] adding connection to [/move_group], count 0
[rospy.internal][INFO] 2017-06-09 18:18:59,443: topic[/attached_collision_object] adding connection to [/move_group], count 0
[rospy.internal][INFO] 2017-06-09 18:18:59,926: topic[/control_markers/update_full] adding connection to [/interactive_marker_proxy], count 0
[rospy.internal][INFO] 2017-06-09 18:19:13,849: topic[/visualization_marker_array] adding connection to [/rosbridge_websocket], count 0
[rospy.internal][INFO] 2017-06-09 18:19:13,894: topic[/control_markers/feedback] adding connection to [http://ip-172-31-26-229:39967/], count 0
[rospy.internal][INFO] 2017-06-09 18:19:30,342: topic[/joint_trajectory] adding connection to [http://ip-172-31-26-229:39201/], count 0
[rospy.internal][INFO] 2017-06-09 18:19:31,172: topic[/motion_planning_goal] adding connection to [/move_arm_7099_1497057569941], count 0
[rospy.internal][INFO] 2017-06-09 18:19:37,328: topic[/tf] adding connection to [http://ip-172-31-26-229:51380/], count 0
[rospy.internal][INFO] 2017-06-09 18:19:37,336: topic[/joint_states] adding connection to [http://ip-172-31-26-229:43708/], count 0
[rospy.internal][INFO] 2017-06-09 18:19:37,519: topic[/joint_command] adding connection to [/robot_sim], count 0
[rospy.internal][INFO] 2017-06-09 18:19:50,858: topic[/control_markers/update_full] removing connection to /interactive_marker_proxy
[rospy.internal][ERROR] 2017-06-09 18:23:26,557: Unable to initiate TCP/IP socket to ip-172-31-26-229:44834 (http://ip-172-31-26-229:39201/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2017-06-09 18:23:27,730: Unknown error initiating TCP/IP socket to ip-172-31-26-229:44834 (http://ip-172-31-26-229:39201/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2017-06-09 18:23:27,735: topic[/joint_trajectory] removing connection to http://ip-172-31-26-229:39201/
[rospy.internal][INFO] 2017-06-09 18:25:02,377: topic[/joint_trajectory] adding connection to [http://ip-172-31-26-229:54832/], count 0
[rospy.internal][INFO] 2017-06-09 18:25:02,382: topic[/motion_planning_goal] adding connection to [/move_arm_1156_1497057901968], count 1
[rospy.internal][INFO] 2017-06-09 18:25:02,387: topic[/motion_planning_goal] removing connection to /move_arm_7099_1497057569941
[rospy.internal][ERROR] 2017-06-09 18:25:19,174: Unable to initiate TCP/IP socket to ip-172-31-26-229:48449 (http://ip-172-31-26-229:54832/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2017-06-09 18:25:20,319: Unknown error initiating TCP/IP socket to ip-172-31-26-229:48449 (http://ip-172-31-26-229:54832/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2017-06-09 18:25:20,323: topic[/joint_trajectory] removing connection to http://ip-172-31-26-229:54832/
[rospy.internal][ERROR] 2017-06-09 18:25:26,524: Unable to initiate TCP/IP socket to ip-172-31-26-229:53171 (http://ip-172-31-26-229:39967/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: Internal error processing topic [/control_markers/feedback]

[rospy.internal][ERROR] 2017-06-09 18:25:27,526: Unable to initiate TCP/IP socket to ip-172-31-26-229:53171 (http://ip-172-31-26-229:39967/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: [/rosbridge_websocket] is not a publisher of [/control_markers/feedback]. Topics are [['/rosout', 'rosgraph_msgs/Log']]

