[rospy.client][INFO] 2017-06-10 23:14:44,921: init_node, name[/marker_control_4128_1497161684873], pid[4128]
[xmlrpc][INFO] 2017-06-10 23:14:44,921: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-06-10 23:14:44,925: Started XML-RPC server [http://ip-172-31-26-229:59401/]
[rospy.impl.masterslave][INFO] 2017-06-10 23:14:44,929: _ready: http://ip-172-31-26-229:59401/
[rospy.init][INFO] 2017-06-10 23:14:44,925: ROS Slave URI: [http://ip-172-31-26-229:59401/]
[xmlrpc][INFO] 2017-06-10 23:14:44,933: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-06-10 23:14:44,933: Registering with master node http://localhost:55108
[rospy.init][INFO] 2017-06-10 23:14:45,036: registered with master
[rospy.rosout][INFO] 2017-06-10 23:14:45,040: initializing /rosout core topic
[rospy.rosout][INFO] 2017-06-10 23:14:45,050: connected to core topic /rosout
[rospy.simtime][INFO] 2017-06-10 23:14:45,054: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-06-10 23:14:45,327: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-06-10 23:14:45,333: topic[/control_markers/update] adding connection to [/interactive_marker_proxy], count 0
[rospy.internal][INFO] 2017-06-10 23:14:45,347: topic[/attached_collision_object] adding connection to [/move_group], count 0
[rospy.internal][INFO] 2017-06-10 23:14:45,351: topic[/collision_object] adding connection to [/move_group], count 0
[rospy.internal][INFO] 2017-06-10 23:14:45,836: topic[/control_markers/update_full] adding connection to [/interactive_marker_proxy], count 0
[rospy.internal][INFO] 2017-06-10 23:14:46,263: topic[/visualization_marker_array] adding connection to [/rosbridge_websocket], count 0
[rospy.internal][INFO] 2017-06-10 23:14:46,376: topic[/control_markers/feedback] adding connection to [http://ip-172-31-26-229:41501/], count 0
[rospy.internal][INFO] 2017-06-10 23:14:53,528: topic[/joint_trajectory] adding connection to [http://ip-172-31-26-229:33558/], count 0
[rospy.internal][INFO] 2017-06-10 23:14:53,532: topic[/motion_planning_goal] adding connection to [/move_arm_4871_1497161693095], count 0
[rospy.internal][INFO] 2017-06-10 23:15:03,345: topic[/joint_states] adding connection to [http://ip-172-31-26-229:57002/], count 0
[rospy.internal][INFO] 2017-06-10 23:15:03,346: topic[/tf] adding connection to [http://ip-172-31-26-229:50004/], count 0
[rospy.internal][INFO] 2017-06-10 23:15:03,594: topic[/joint_command] adding connection to [/robot_sim], count 0
[rospy.internal][INFO] 2017-06-10 23:15:11,976: topic[/control_markers/update_full] removing connection to /interactive_marker_proxy
[rospy.internal][ERROR] 2017-06-10 23:16:17,020: Unable to initiate TCP/IP socket to ip-172-31-26-229:46103 (http://ip-172-31-26-229:33558/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rosout][WARNING] 2017-06-10 23:16:17,752: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][ERROR] 2017-06-10 23:16:17,756: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 321, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 365, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][WARNING] 2017-06-10 23:16:18,164: Unknown error initiating TCP/IP socket to ip-172-31-26-229:46103 (http://ip-172-31-26-229:33558/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2017-06-10 23:16:18,168: topic[/joint_trajectory] removing connection to http://ip-172-31-26-229:33558/
[rospy.internal][INFO] 2017-06-10 23:17:06,842: topic[/joint_trajectory] adding connection to [http://ip-172-31-26-229:35933/], count 0
[rospy.internal][INFO] 2017-06-10 23:17:06,850: topic[/motion_planning_goal] adding connection to [/move_arm_26261_1497161826456], count 1
[rospy.internal][INFO] 2017-06-10 23:17:21,249: topic[/motion_planning_goal] removing connection to /move_arm_4871_1497161693095
[rospy.internal][ERROR] 2017-06-10 23:19:19,161: Unable to initiate TCP/IP socket to ip-172-31-26-229:34724 (http://ip-172-31-26-229:35933/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2017-06-10 23:19:20,311: Unknown error initiating TCP/IP socket to ip-172-31-26-229:34724 (http://ip-172-31-26-229:35933/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2017-06-10 23:19:20,315: topic[/joint_trajectory] removing connection to http://ip-172-31-26-229:35933/
