[rospy.client][INFO] 2017-06-09 23:43:53,512: init_node, name[/move_arm_13395_1497077033473], pid[13395]
[xmlrpc][INFO] 2017-06-09 23:43:53,513: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-06-09 23:43:53,517: Started XML-RPC server [http://ip-172-31-19-100:60372/]
[rospy.init][INFO] 2017-06-09 23:43:53,517: ROS Slave URI: [http://ip-172-31-19-100:60372/]
[rospy.impl.masterslave][INFO] 2017-06-09 23:43:53,521: _ready: http://ip-172-31-19-100:60372/
[xmlrpc][INFO] 2017-06-09 23:43:53,536: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-06-09 23:43:53,537: Registering with master node http://localhost:60180
[rospy.init][INFO] 2017-06-09 23:43:53,625: registered with master
[rospy.rosout][INFO] 2017-06-09 23:43:53,628: initializing /rosout core topic
[rospy.rosout][INFO] 2017-06-09 23:43:53,642: connected to core topic /rosout
[rospy.simtime][INFO] 2017-06-09 23:43:53,646: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-06-09 23:43:53,877: topic[/joint_states] adding connection to [http://ip-172-31-19-100:57153/], count 0
[rospy.internal][INFO] 2017-06-09 23:43:53,878: topic[/motion_planning_goal] adding connection to [http://ip-172-31-19-100:41828/], count 0
[rospy.internal][INFO] 2017-06-09 23:43:53,879: topic[/joint_trajectory] adding connection to [/marker_control_8946_1497076857451], count 0
[rospy.internal][INFO] 2017-06-09 23:43:54,752: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-06-09 23:43:54,756: topic[/joint_trajectory] adding connection to [/robot_sim], count 1
[rospy.internal][INFO] 2017-06-09 23:43:54,792: topic[/attached_collision_object] adding connection to [/move_group], count 0
[rospy.internal][INFO] 2017-06-09 23:43:54,797: topic[/collision_object] adding connection to [/move_group], count 0
[rospy.core][INFO] 2017-06-09 23:46:42,466: signal_shutdown [signal-2]
[rospy.internal][INFO] 2017-06-09 23:46:42,518: topic[/collision_object] removing connection to /move_group
[rospy.internal][INFO] 2017-06-09 23:46:42,522: topic[/joint_trajectory] removing connection to /marker_control_8946_1497076857451
[rospy.internal][INFO] 2017-06-09 23:46:42,526: topic[/joint_trajectory] removing connection to /robot_sim
[rospy.internal][INFO] 2017-06-09 23:46:42,530: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-06-09 23:46:42,533: topic[/attached_collision_object] removing connection to /move_group
[rospy.internal][INFO] 2017-06-09 23:46:42,537: topic[/motion_planning_goal] removing connection to http://ip-172-31-19-100:41828/
[rospy.internal][INFO] 2017-06-09 23:46:42,541: topic[/joint_states] removing connection to http://ip-172-31-19-100:57153/
[rospy.impl.masterslave][INFO] 2017-06-09 23:46:42,545: signal-2
[rospy.topics][WARNING] 2017-06-09 23:46:42,557: during shutdown, bad callback: <bound method MoveArm.move_arm_cb of <__main__.MoveArm object at 0x7f26a133e410>>
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 720, in _invoke_callback
    cb(msg)
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 361, in move_arm_cb
    return
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 346, in project_plan
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 293, in motion_plan
    #    new_node = TreeNode(point)
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 259, in is_collision_free
    #print('is_collision_free: state_valid={}'.format(self.is_state_valid(check_point)))
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 203, in is_state_valid
    res = self.state_valid_service(req)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 517, in call
    raise ServiceException("service [%s] returned no response"%self.resolved_name)
ServiceException: service [/check_state_validity] returned no response

[rospy.core][INFO] 2017-06-09 23:46:43,622: signal_shutdown [atexit]
