[rospy.client][INFO] 2017-06-09 18:43:23,373: init_node, name[/move_arm_15160_1497059003331], pid[15160]
[xmlrpc][INFO] 2017-06-09 18:43:23,374: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-06-09 18:43:23,377: Started XML-RPC server [http://ip-172-31-19-100:60967/]
[rospy.init][INFO] 2017-06-09 18:43:23,377: ROS Slave URI: [http://ip-172-31-19-100:60967/]
[rospy.impl.masterslave][INFO] 2017-06-09 18:43:23,381: _ready: http://ip-172-31-19-100:60967/
[xmlrpc][INFO] 2017-06-09 18:43:23,399: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-06-09 18:43:23,399: Registering with master node http://localhost:37427
[rospy.init][INFO] 2017-06-09 18:43:23,494: registered with master
[rospy.rosout][INFO] 2017-06-09 18:43:23,502: initializing /rosout core topic
[rospy.rosout][INFO] 2017-06-09 18:43:23,511: connected to core topic /rosout
[rospy.simtime][INFO] 2017-06-09 18:43:23,516: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-06-09 18:43:23,741: topic[/motion_planning_goal] adding connection to [http://ip-172-31-19-100:38675/], count 0
[rospy.internal][INFO] 2017-06-09 18:43:23,742: topic[/joint_states] adding connection to [http://ip-172-31-19-100:47311/], count 0
[rospy.internal][INFO] 2017-06-09 18:43:23,745: topic[/joint_trajectory] adding connection to [/marker_control_13450_1497058913346], count 0
[rospy.internal][INFO] 2017-06-09 18:43:24,655: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-06-09 18:43:24,659: topic[/joint_trajectory] adding connection to [/robot_sim], count 1
[rospy.internal][INFO] 2017-06-09 18:43:24,697: topic[/collision_object] adding connection to [/move_group], count 0
[rospy.internal][INFO] 2017-06-09 18:43:24,701: topic[/attached_collision_object] adding connection to [/move_group], count 0
[rospy.core][INFO] 2017-06-09 18:50:41,284: signal_shutdown [signal-2]
[rospy.internal][INFO] 2017-06-09 18:50:41,316: topic[/collision_object] removing connection to /move_group
[rospy.internal][INFO] 2017-06-09 18:50:41,321: topic[/joint_trajectory] removing connection to /marker_control_13450_1497058913346
[rospy.internal][INFO] 2017-06-09 18:50:41,326: topic[/joint_trajectory] removing connection to /robot_sim
[rospy.internal][INFO] 2017-06-09 18:50:41,330: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-06-09 18:50:41,335: topic[/attached_collision_object] removing connection to /move_group
[rospy.internal][INFO] 2017-06-09 18:50:41,338: topic[/motion_planning_goal] removing connection to http://ip-172-31-19-100:38675/
[rospy.internal][INFO] 2017-06-09 18:50:41,345: topic[/joint_states] removing connection to http://ip-172-31-19-100:47311/
[rospy.impl.masterslave][INFO] 2017-06-09 18:50:41,348: signal-2
[rospy.topics][WARNING] 2017-06-09 18:50:41,360: during shutdown, bad callback: <bound method MoveArm.move_arm_cb of <__main__.MoveArm object at 0x7f581fedd3d0>>
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 720, in _invoke_callback
    cb(msg)
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 339, in move_arm_cb
    return
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 324, in project_plan
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 280, in motion_plan
    new_node = TreeNode(point)
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 250, in is_collision_free
    print('is_collision_free: state_valid={}'.format(self.is_state_valid(check_point)))
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 203, in is_state_valid
    res = self.state_valid_service(req)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 517, in call
    raise ServiceException("service [%s] returned no response"%self.resolved_name)
ServiceException: service [/check_state_validity] returned no response

[rospy.core][INFO] 2017-06-09 18:50:41,918: signal_shutdown [atexit]
