[rospy.client][INFO] 2017-06-05 18:59:31,256: init_node, name[/cartesian_control_9131_1496714371222], pid[9131]
[xmlrpc][INFO] 2017-06-05 18:59:31,256: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-06-05 18:59:31,260: Started XML-RPC server [http://ip-172-31-26-229:45391/]
[rospy.init][INFO] 2017-06-05 18:59:31,260: ROS Slave URI: [http://ip-172-31-26-229:45391/]
[rospy.impl.masterslave][INFO] 2017-06-05 18:59:31,264: _ready: http://ip-172-31-26-229:45391/
[xmlrpc][INFO] 2017-06-05 18:59:31,277: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-06-05 18:59:31,277: Registering with master node http://localhost:56640
[rospy.init][INFO] 2017-06-05 18:59:31,374: registered with master
[rospy.rosout][INFO] 2017-06-05 18:59:31,381: initializing /rosout core topic
[rospy.rosout][INFO] 2017-06-05 18:59:31,393: connected to core topic /rosout
[rospy.simtime][INFO] 2017-06-05 18:59:31,397: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-06-05 18:59:31,456: topic[/joint_states] adding connection to [http://ip-172-31-26-229:40167/], count 0
[rospy.internal][INFO] 2017-06-05 18:59:31,599: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-06-05 18:59:31,683: topic[/joint_command] adding connection to [/robot_sim], count 0
[rospy.internal][INFO] 2017-06-05 18:59:31,688: topic[/control_markers/update] adding connection to [/interactive_marker_proxy], count 0
[rospy.internal][INFO] 2017-06-05 18:59:31,889: topic[/control_markers/update_full] adding connection to [/interactive_marker_proxy], count 0
[rospy.internal][INFO] 2017-06-05 18:59:31,928: topic[/control_markers/update_full] removing connection to /interactive_marker_proxy
[rospy.internal][INFO] 2017-06-05 18:59:46,522: topic[/control_markers/feedback] adding connection to [http://ip-172-31-26-229:45960/], count 0
[rospy.internal][INFO] 2017-06-05 19:01:05,506: topic[/cartesian_command] adding connection to [/cartesian_control_9967_1496714465264], count 0
[rospy.internal][INFO] 2017-06-05 19:01:05,510: topic[/redundancy_command] adding connection to [/cartesian_control_9967_1496714465264], count 0
[rospy.internal][INFO] 2017-06-05 19:01:44,347: topic[/cartesian_command] removing connection to /cartesian_control_9967_1496714465264
[rosout][WARNING] 2017-06-05 19:01:44,576: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][ERROR] 2017-06-05 19:01:44,580: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 321, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 365, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2017-06-05 19:03:32,046: topic[/redundancy_command] removing connection to /cartesian_control_9967_1496714465264
[rospy.internal][ERROR] 2017-06-05 19:04:01,300: Unable to initiate TCP/IP socket to ip-172-31-26-229:40981 (http://ip-172-31-26-229:45960/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: Internal error processing topic [/control_markers/feedback]

[rospy.internal][ERROR] 2017-06-05 19:04:02,301: Unable to initiate TCP/IP socket to ip-172-31-26-229:40981 (http://ip-172-31-26-229:45960/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: [/rosbridge_websocket] is not a publisher of [/control_markers/feedback]. Topics are [['/rosout', 'rosgraph_msgs/Log']]

